application: charlesperrycom-hrd
version: 4
runtime: python27
api_version: 1

builtins:
- appstats: on

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico

- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt

- url: /media
  static_dir: media

- url: /.*
  script: main.py

derived_file_type:
- python_precompiled

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^django.zip
- ^non_gae_indicator

threadsafe:
- yes

libraries:
- name: django
  version: "1.4"
  
